info:
  version: 1.0.2
  description: LB initial local configuration

configuration:
  lbName: LB # the name of this LB
  ngapIp: "10.162.149.214"    
  ngapListenPort: 48484
  ngapLbToAmfPort: 23232
  amfNgapIpList: 
    - 10.162.149.189
    #- 127.0.0.1
  amfNgapPortList: 
    - 38412
    #- 38000

# # the kind of log output
#   # debugLevel: how detailed to output, value: trace, debug, info, warn, error, fatal, panic
#   # ReportCaller: enable the caller report or not, value: true or false
logger:
  AMF:
    debugLevel: trace
    ReportCaller: false
  NGAP:
    debugLevel: trace
    ReportCaller: false

