info:
  version: 1.0.2
  description: LB initial local configuration

configuration:
  lbName: LB # the name of this LB
  ngapIp: "10.162.149.214" # IP of this LB 
  ngapListenPort: 48484 # port of this LB that listens to incoming GNB connections 
  ngapLbToAmfPort: 23232  # port of this LB that connects to the AMFs 
  differentAmfTypes: 1 # 1, 2, 3 
  registrationAmfNgapIpList: # on launch known Registration-AMF-IPs (default port: 38412) (use with 1-3 types)
    # - 10.162.149.172
    - 10.162.149.214
  deregistrationAmfNgapIpList: # on launch known Deregistration-AMF-IPs (default port: 38412) (use with 2 and 3 types)
    # - 10.162.149.172
    # - 10.162.149.214
  regularAmfNgapIpList: # on launch known Regular-AMF-IPs (default port: 38412) (use only with 3 types as AMF between registration and deregistration)
    # - 10.162.149.172
    # - 10.162.149.214
  servedGuamiList: # Guami (Globally Unique AMF ID) list supported by this AMF
    # <GUAMI> = <MCC><MNC><AMF ID>
    - plmnId: # Public Land Mobile Network ID, <PLMN ID> = <MCC><MNC>
        mcc: 208 # Mobile Country Code (3 digits string, digit: 0~9)
        mnc: 93 # Mobile Network Code (2 or 3 digits string, digit: 0~9)
      amfId: cafe00 # AMF identifier (3 bytes hex string, range: 000000~FFFFFF)
  plmnSupportList: # the PLMNs (Public land mobile network) list supported by this AMF
    - plmnId: # Public Land Mobile Network ID, <PLMN ID> = <MCC><MNC>
        mcc: 208 # Mobile Country Code (3 digits string, digit: 0~9)
        mnc: 93 # Mobile Network Code (2 or 3 digits string, digit: 0~9)
      snssaiList: # the S-NSSAI (Single Network Slice Selection Assistance Information) list supported by this AMF
        - sst: 1 # Slice/Service Type (uinteger, range: 0~255)
          sd: 010203 # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
        - sst: 1 # Slice/Service Type (uinteger, range: 0~255)
          sd: 112233 # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
  metricsLevel: 3 # levels (make sure to be on debugLevel info or lower): 
    # 0 (no metrics), 
    # 1 (time lost due to LB per UE), 
    # 2 (routing: enables LB internal tracking of UE states, routings, and message specific timings)   
    # 3 (1 and 2)
  continuesAmfRegistration: true # true for continues accepting AMFs for registration

# # the kind of log output
#   # debugLevel: how detailed to output, value: trace, debug, info, warn, error, fatal, panic
#   # ReportCaller: enable the caller report or not, value: true or false
logger:
  LB:
    debugLevel: info
    ReportCaller: false

